FROM golang:1.10
COPY . /go/src/github.com/containerbuilding/cbi
RUN go build -o /cbid -a -tags netgo -installsuffix netgo --ldflags '-extldflags "-static"' github.com/containerbuilding/cbi/cmd/cbid

FROM debian:9
COPY --from=0 /cbid /cbid
ENTRYPOINT ["/cbid"]
